import { WebNavbar } from "@/layout/WebNavbar";
import { WebFooter } from "@/layout/WebFooter";
import { FileCheck, Shield, Award, CreditCard, AlertCircle } from "lucide-react";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background text-foreground font-sans selection:bg-primary/30 selection:text-foreground">
      <WebNavbar />

      <main className="py-20 px-6 max-w-4xl mx-auto space-y-12">
        {/* Page Header */}
        <div className="space-y-4 text-center sm:text-left border-b border-border pb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary border border-primary/20 text-xs font-mono font-bold uppercase tracking-wider">
            <FileCheck className="w-3.5 h-3.5" /> Enterprise Commercial Agreement
          </div>
          <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-foreground">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground font-mono">
            Last Modified: March 1, 2026 • Effective Immediately
          </p>
        </div>

        {/* Customer Code Ownership Banner */}
        <div className="skeuo-glass-card rounded-2xl p-6 border-2 border-primary/40 space-y-3 shadow-lg">
          <div className="flex items-center gap-2 text-primary font-bold text-sm">
            <Award className="w-4 h-4" />
            <span>100% Intellectual Property Ownership of Generated Code</span>
          </div>
          <p className="text-xs sm:text-sm text-foreground/90 leading-relaxed">
            All code modifications, AST patches, test scripts, and git commits generated by the Bee Autonomous Co-Engineer are your exclusive intellectual property. Bee claims zero copyright, license rights, or royalties over your software deliverables.
          </p>
        </div>

        {/* Terms Sections */}
        <div className="space-y-10 text-xs sm:text-sm leading-relaxed text-muted-foreground">
          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-foreground flex items-center gap-2">
              <Shield className="w-4 h-4 text-primary" /> 1. Acceptance & Service Scope
            </h2>
            <p>
              By accessing or using the Bee platform (including the Web landing suite, Desktop Console, CLI, FastMCP Sidecar, and Cloud APIs), you agree to be bound by these Terms of Service. If you are entering into this agreement on behalf of a company, organization, or legal entity, you represent that you possess the authority to bind such entity.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-foreground flex items-center gap-2">
              <CreditCard className="w-4 h-4 text-primary" /> 2. Subscriptions, Stripe Billing & Cancellation
            </h2>
            <p>
              Bee offers Free Starter, Pro Co-Engineer ($49/month), and Enterprise Team ($249/month) subscription tiers:
            </p>
            <ul className="list-disc pl-5 space-y-1.5 text-foreground/80">
              <li><strong>Billing Cycle:</strong> Subscriptions are billed in advance on a recurring monthly or annual basis via Stripe.</li>
              <li><strong>Cancellation:</strong> You may cancel your subscription at any time via the Stripe Customer Portal inside the Console. Your workspace retains Pro features until the conclusion of the current billing cycle.</li>
              <li><strong>Refund Policy:</strong> We provide a 14-day no-questions-asked refund guarantee on initial Pro and Team plan upgrades.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-foreground flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-primary" /> 3. Human-in-the-Loop & Approval Gates
            </h2>
            <p>
              While Bee executes autonomous debugging, testing, and AST repair, <strong>all destructive actions (such as git branch commits, cloud infrastructure deployments, and schema migrations) require explicit human sign-off via Zero-Trust Approval Gates</strong>. You remain solely responsible for validating generated code before deploying to production environments.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base sm:text-lg font-bold text-foreground flex items-center gap-2">
              <FileCheck className="w-4 h-4 text-primary" /> 4. Service Level Agreement & Disclaimers
            </h2>
            <p>
              Enterprise tiers include a 99.9% uptime Service Level Agreement (SLA) for our Cloud Sync and Webhook Ingress infrastructure. The platform is provided on an "as is" and "as available" basis. To the maximum extent permitted by applicable law, Bee disclaims all implied warranties of merchantability or fitness for a particular purpose.
            </p>
          </section>
        </div>
      </main>

      <WebFooter />
    </div>
  );
}
